security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\Authenticator\OtpLoginAuthenticator
            logout:
                path: /connexion/deconnexion

    access_control:
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/sync, roles: ROLE_USER }

when@test:
    security:
        role_hierarchy:
            ROLE_ADMIN: ROLE_USER
